name: Artifact

on: [push]

env:
  PATCH: 1

jobs:
  main:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the code 
        uses: actions/checkout@v2
        
      - name: Set Track
        id: set_track
        run: |
          if [ ${{ env.PATCH }} -gt 0 ]; then
            echo "track=Mobile-RC-hotfix" >> $GITHUB_OUTPUT
          else
           echo "track=Mobile-RC" >> $GITHUB_OUTPUT
          fi
      - name: Print Track
        run: |
          echo "track: ${{ steps.set_track.outputs.track }}"
